#!/usr/bin/awk -f

# ./mk_theme.sh ctest \
# '^\s*[0-9]+/[0-9]+ Test\s+#[0-9]+: (.*)\s+\.+\s+(Passed)' 'G' -- \
# '^\s*[0-9]+/[0-9]+ Test\s+#[0-9]+: (.*)\s+\.+(\*{3}.*)\s+.*' 'R'

# gawk profile, created Mon Feb 20 23:48:31 2017

# BEGIN rule(s)

BEGIN {
}

# Rule(s)

{
	s = ""
	if (match($0, /^\s*[0-9]+\/[0-9]+ Test\s+#[0-9]+: (.*)\s+\.+\s+(Passed)/, a)) {
		n = length(a) / 3
		if (n == 1) {
			i = 0
			ic = 0
			s = s substr($0, 0, RSTART - 1) "\033[;32;1m" a[i] "\033[0m"
		} else {
			c = ""
			p = 1
			for (i = 1; i < n; ++i) {
				start = a[i, "start"]
				if (start == null) {
					++n
					continue
				}
				ic = i - 1
				s = s substr($0, p, start - p) "\033[;32;1m" a[i] "\033[0m"
				p = start + a[i, "length"]
			}
			s = s substr($0, p, RSTART + RLENGTH - p)
		}
		$0 = substr($0, RLENGTH + RSTART)
	} else {
		if (match($0, /^\s*[0-9]+\/[0-9]+ Test\s+#[0-9]+: (.*)\s+\.+(\*{3}.*)\s+.*/, a)) {
			n = length(a) / 3
			if (n == 1) {
				i = 0
				ic = 0
				s = s substr($0, 0, RSTART - 1) "\033[;31;1m" a[i] "\033[0m"
			} else {
				c = ""
				p = 1
				for (i = 1; i < n; ++i) {
					start = a[i, "start"]
					if (start == null) {
						++n
						continue
					}
					ic = i - 1
					s = s substr($0, p, start - p) "\033[;31;1m" a[i] "\033[0m"
					p = start + a[i, "length"]
				}
				s = s substr($0, p, RSTART + RLENGTH - p)
			}
			$0 = substr($0, RLENGTH + RSTART)
		}
	}
	print s $0
}

