#!/usr/bin/awk -f
# ./mk_theme.sh valgrind \^\(==\[0-9\]+==\s\{1\}\)\(Memcheck\|Copyright\|Using\|Rerun\|Use\ --\)\(.\*\)\$ b -- \^\(==\[0-9\]+==\s\{1\}\)\(Warning\)\(.\*\)\$ U -- \^\(==\[0-9\]+==\s\{1\}Command:\ \)\(\S\*\)\(.\*\)\$ g W -- \^\(==\[0-9\]+==\s\{1\}\)\(HEAP\ SUMMARY:\|All\ heap\ blocks\ were\ freed\)\(.\*\)\$ G -- \^\(==\[0-9\]+==\s\{1\}\S+.\*\)\$ B,r -- \^==\[0-9\]+==\s\{2\}\(\S+.\*\)\$ Y -- \^==\[0-9\]+==\s\{4\}\(\[atby\]\{2\}\)\ \(0x0\):\ \(\\?\{3\}\) b y B,r -- \^==\[0-9\]+==\s\{4\}\(\[atby\]\{2\}\)\ \(0x\)\(\[\^:\]\*:\)\ \S+ B B B -- \\(in\ \(.\*\)\\) C -- \\(\(\[\^\.\]\*\.\[\^:\]+\):\(\[0-9\]+\)\\) W y -- \^==\[0-9\]+==\s\{4\}\(definitely\ lost\):\ .\*\ \(in\)\ .\* B,r -- \^==\[0-9\]+==\s\{4\}\(indirectly\ lost\):\ .\*\ \(in\)\ .\* Y -- \^==\[0-9\]+==\s\{6\}\(possibly\ lost\):\ .\*\ \(in\)\ .\* Y -- \^==\[0-9\]+==\s\{4\}\(still\ reachable\):\ .\*\ \(in\)\ .\* G -- \^==\[0-9\]+==\s\{9\}\(suppressed\):\ .\*\ \(in\)\ .\* C

# gawk profile, created Sun Feb 19 23:46:41 2017

# BEGIN rule(s)

BEGIN {
	colors0[0] = ";34"
	nb_colors0 = 1
	colors1[0] = ";4;1"
	nb_colors1 = 1
	colors2[0] = ";32"
	colors2[1] = ";97;1"
	nb_colors2 = 2
	colors3[0] = ";32;1"
	nb_colors3 = 1
	colors4[0] = ";34;1;31"
	nb_colors4 = 1
	colors5[0] = ";33;1"
	nb_colors5 = 1
	colors6[0] = ";34"
	colors6[1] = ";33"
	colors6[2] = ";34;1;31"
	nb_colors6 = 3
	colors7[0] = ";34;1"
	colors7[1] = ";34;1"
	colors7[2] = ";34;1"
	nb_colors7 = 3
	colors8[0] = ";36;1"
	nb_colors8 = 1
	colors9[0] = ";97;1"
	colors9[1] = ";33"
	nb_colors9 = 2
	colors10[0] = ";34;1;31"
	nb_colors10 = 1
	colors11[0] = ";33;1"
	nb_colors11 = 1
	colors12[0] = ";33;1"
	nb_colors12 = 1
	colors13[0] = ";32;1"
	nb_colors13 = 1
	colors14[0] = ";36;1"
	nb_colors14 = 1
}

# Rule(s)

{
	s = ""
	if (match($0, /^(==[0-9]+==\s{1})(Memcheck|Copyright|Using|Rerun|Use --)(.*)$/, a)) {
		n = length(a) / 3
		if (n == 1) {
			i = 0
			ic = 0
			s = s substr($0, 0, RSTART - 1) "\033[" colors0[ic % nb_colors0] "m" a[i] "\033[0m"
		} else {
			c = ""
			p = 1
			for (i = 1; i < n; ++i) {
				start = a[i, "start"]
				if (start == null) {
					++n
					continue
				}
				ic = i - 1
				s = s substr($0, p, start - p) "\033[" colors0[ic % nb_colors0] "m" a[i] "\033[0m"
				p = start + a[i, "length"]
			}
			s = s substr($0, p, RSTART + RLENGTH - p)
		}
		$0 = substr($0, RLENGTH + RSTART)
	} else {
		if (match($0, /^(==[0-9]+==\s{1})(Warning)(.*)$/, a)) {
			n = length(a) / 3
			if (n == 1) {
				i = 0
				ic = 0
				s = s substr($0, 0, RSTART - 1) "\033[" colors1[ic % nb_colors1] "m" a[i] "\033[0m"
			} else {
				c = ""
				p = 1
				for (i = 1; i < n; ++i) {
					start = a[i, "start"]
					if (start == null) {
						++n
						continue
					}
					ic = i - 1
					s = s substr($0, p, start - p) "\033[" colors1[ic % nb_colors1] "m" a[i] "\033[0m"
					p = start + a[i, "length"]
				}
				s = s substr($0, p, RSTART + RLENGTH - p)
			}
			$0 = substr($0, RLENGTH + RSTART)
		} else {
			if (match($0, /^(==[0-9]+==\s{1}Command: )(\S*)(.*)$/, a)) {
				n = length(a) / 3
				if (n == 1) {
					i = 0
					ic = 0
					s = s substr($0, 0, RSTART - 1) "\033[" colors2[ic % nb_colors2] "m" a[i] "\033[0m"
				} else {
					c = ""
					p = 1
					for (i = 1; i < n; ++i) {
						start = a[i, "start"]
						if (start == null) {
							++n
							continue
						}
						ic = i - 1
						s = s substr($0, p, start - p) "\033[" colors2[ic % nb_colors2] "m" a[i] "\033[0m"
						p = start + a[i, "length"]
					}
					s = s substr($0, p, RSTART + RLENGTH - p)
				}
				$0 = substr($0, RLENGTH + RSTART)
			} else {
				if (match($0, /^(==[0-9]+==\s{1})(HEAP SUMMARY:|All heap blocks were freed)(.*)$/, a)) {
					n = length(a) / 3
					if (n == 1) {
						i = 0
						ic = 0
						s = s substr($0, 0, RSTART - 1) "\033[" colors3[ic % nb_colors3] "m" a[i] "\033[0m"
					} else {
						c = ""
						p = 1
						for (i = 1; i < n; ++i) {
							start = a[i, "start"]
							if (start == null) {
								++n
								continue
							}
							ic = i - 1
							s = s substr($0, p, start - p) "\033[" colors3[ic % nb_colors3] "m" a[i] "\033[0m"
							p = start + a[i, "length"]
						}
						s = s substr($0, p, RSTART + RLENGTH - p)
					}
					$0 = substr($0, RLENGTH + RSTART)
				} else {
					if (match($0, /^(==[0-9]+==\s{1}\S+.*)$/, a)) {
						n = length(a) / 3
						if (n == 1) {
							i = 0
							ic = 0
							s = s substr($0, 0, RSTART - 1) "\033[" colors4[ic % nb_colors4] "m" a[i] "\033[0m"
						} else {
							c = ""
							p = 1
							for (i = 1; i < n; ++i) {
								start = a[i, "start"]
								if (start == null) {
									++n
									continue
								}
								ic = i - 1
								s = s substr($0, p, start - p) "\033[" colors4[ic % nb_colors4] "m" a[i] "\033[0m"
								p = start + a[i, "length"]
							}
							s = s substr($0, p, RSTART + RLENGTH - p)
						}
						$0 = substr($0, RLENGTH + RSTART)
					} else {
						if (match($0, /^==[0-9]+==\s{2}(\S+.*)$/, a)) {
							n = length(a) / 3
							if (n == 1) {
								i = 0
								ic = 0
								s = s substr($0, 0, RSTART - 1) "\033[" colors5[ic % nb_colors5] "m" a[i] "\033[0m"
							} else {
								c = ""
								p = 1
								for (i = 1; i < n; ++i) {
									start = a[i, "start"]
									if (start == null) {
										++n
										continue
									}
									ic = i - 1
									s = s substr($0, p, start - p) "\033[" colors5[ic % nb_colors5] "m" a[i] "\033[0m"
									p = start + a[i, "length"]
								}
								s = s substr($0, p, RSTART + RLENGTH - p)
							}
							$0 = substr($0, RLENGTH + RSTART)
						} else {
							if (match($0, /^==[0-9]+==\s{4}([atby]{2}) (0x0): (\?{3})/, a)) {
								n = length(a) / 3
								if (n == 1) {
									i = 0
									ic = 0
									s = s substr($0, 0, RSTART - 1) "\033[" colors6[ic % nb_colors6] "m" a[i] "\033[0m"
								} else {
									c = ""
									p = 1
									for (i = 1; i < n; ++i) {
										start = a[i, "start"]
										if (start == null) {
											++n
											continue
										}
										ic = i - 1
										s = s substr($0, p, start - p) "\033[" colors6[ic % nb_colors6] "m" a[i] "\033[0m"
										p = start + a[i, "length"]
									}
									s = s substr($0, p, RSTART + RLENGTH - p)
								}
								$0 = substr($0, RLENGTH + RSTART)
							} else {
								if (match($0, /^==[0-9]+==\s{4}([atby]{2}) (0x)([^:]*:) \S+/, a)) {
									n = length(a) / 3
									if (n == 1) {
										i = 0
										ic = 0
										s = s substr($0, 0, RSTART - 1) "\033[" colors7[ic % nb_colors7] "m" a[i] "\033[0m"
									} else {
										c = ""
										p = 1
										for (i = 1; i < n; ++i) {
											start = a[i, "start"]
											if (start == null) {
												++n
												continue
											}
											ic = i - 1
											s = s substr($0, p, start - p) "\033[" colors7[ic % nb_colors7] "m" a[i] "\033[0m"
											p = start + a[i, "length"]
										}
										s = s substr($0, p, RSTART + RLENGTH - p)
									}
									$0 = substr($0, RLENGTH + RSTART)
								} else {
									if (match($0, /\(in (.*)\)/, a)) {
										n = length(a) / 3
										if (n == 1) {
											i = 0
											ic = 0
											s = s substr($0, 0, RSTART - 1) "\033[" colors8[ic % nb_colors8] "m" a[i] "\033[0m"
										} else {
											c = ""
											p = 1
											for (i = 1; i < n; ++i) {
												start = a[i, "start"]
												if (start == null) {
													++n
													continue
												}
												ic = i - 1
												s = s substr($0, p, start - p) "\033[" colors8[ic % nb_colors8] "m" a[i] "\033[0m"
												p = start + a[i, "length"]
											}
											s = s substr($0, p, RSTART + RLENGTH - p)
										}
										$0 = substr($0, RLENGTH + RSTART)
									} else {
										if (match($0, /\(([^\.]*\.[^:]+):([0-9]+)\)/, a)) {
											n = length(a) / 3
											if (n == 1) {
												i = 0
												ic = 0
												s = s substr($0, 0, RSTART - 1) "\033[" colors9[ic % nb_colors9] "m" a[i] "\033[0m"
											} else {
												c = ""
												p = 1
												for (i = 1; i < n; ++i) {
													start = a[i, "start"]
													if (start == null) {
														++n
														continue
													}
													ic = i - 1
													s = s substr($0, p, start - p) "\033[" colors9[ic % nb_colors9] "m" a[i] "\033[0m"
													p = start + a[i, "length"]
												}
												s = s substr($0, p, RSTART + RLENGTH - p)
											}
											$0 = substr($0, RLENGTH + RSTART)
										} else {
											if (match($0, /^==[0-9]+==\s{4}(definitely lost): .* (in) .*/, a)) {
												n = length(a) / 3
												if (n == 1) {
													i = 0
													ic = 0
													s = s substr($0, 0, RSTART - 1) "\033[" colors10[ic % nb_colors10] "m" a[i] "\033[0m"
												} else {
													c = ""
													p = 1
													for (i = 1; i < n; ++i) {
														start = a[i, "start"]
														if (start == null) {
															++n
															continue
														}
														ic = i - 1
														s = s substr($0, p, start - p) "\033[" colors10[ic % nb_colors10] "m" a[i] "\033[0m"
														p = start + a[i, "length"]
													}
													s = s substr($0, p, RSTART + RLENGTH - p)
												}
												$0 = substr($0, RLENGTH + RSTART)
											} else {
												if (match($0, /^==[0-9]+==\s{4}(indirectly lost): .* (in) .*/, a)) {
													n = length(a) / 3
													if (n == 1) {
														i = 0
														ic = 0
														s = s substr($0, 0, RSTART - 1) "\033[" colors11[ic % nb_colors11] "m" a[i] "\033[0m"
													} else {
														c = ""
														p = 1
														for (i = 1; i < n; ++i) {
															start = a[i, "start"]
															if (start == null) {
																++n
																continue
															}
															ic = i - 1
															s = s substr($0, p, start - p) "\033[" colors11[ic % nb_colors11] "m" a[i] "\033[0m"
															p = start + a[i, "length"]
														}
														s = s substr($0, p, RSTART + RLENGTH - p)
													}
													$0 = substr($0, RLENGTH + RSTART)
												} else {
													if (match($0, /^==[0-9]+==\s{6}(possibly lost): .* (in) .*/, a)) {
														n = length(a) / 3
														if (n == 1) {
															i = 0
															ic = 0
															s = s substr($0, 0, RSTART - 1) "\033[" colors12[ic % nb_colors12] "m" a[i] "\033[0m"
														} else {
															c = ""
															p = 1
															for (i = 1; i < n; ++i) {
																start = a[i, "start"]
																if (start == null) {
																	++n
																	continue
																}
																ic = i - 1
																s = s substr($0, p, start - p) "\033[" colors12[ic % nb_colors12] "m" a[i] "\033[0m"
																p = start + a[i, "length"]
															}
															s = s substr($0, p, RSTART + RLENGTH - p)
														}
														$0 = substr($0, RLENGTH + RSTART)
													} else {
														if (match($0, /^==[0-9]+==\s{4}(still reachable): .* (in) .*/, a)) {
															n = length(a) / 3
															if (n == 1) {
																i = 0
																ic = 0
																s = s substr($0, 0, RSTART - 1) "\033[" colors13[ic % nb_colors13] "m" a[i] "\033[0m"
															} else {
																c = ""
																p = 1
																for (i = 1; i < n; ++i) {
																	start = a[i, "start"]
																	if (start == null) {
																		++n
																		continue
																	}
																	ic = i - 1
																	s = s substr($0, p, start - p) "\033[" colors13[ic % nb_colors13] "m" a[i] "\033[0m"
																	p = start + a[i, "length"]
																}
																s = s substr($0, p, RSTART + RLENGTH - p)
															}
															$0 = substr($0, RLENGTH + RSTART)
														} else {
															if (match($0, /^==[0-9]+==\s{9}(suppressed): .* (in) .*/, a)) {
																n = length(a) / 3
																if (n == 1) {
																	i = 0
																	ic = 0
																	s = s substr($0, 0, RSTART - 1) "\033[" colors14[ic % nb_colors14] "m" a[i] "\033[0m"
																} else {
																	c = ""
																	p = 1
																	for (i = 1; i < n; ++i) {
																		start = a[i, "start"]
																		if (start == null) {
																			++n
																			continue
																		}
																		ic = i - 1
																		s = s substr($0, p, start - p) "\033[" colors14[ic % nb_colors14] "m" a[i] "\033[0m"
																		p = start + a[i, "length"]
																	}
																	s = s substr($0, p, RSTART + RLENGTH - p)
																}
																$0 = substr($0, RLENGTH + RSTART)
															}
														}
													}
												}
											}
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}
	print s $0
}

