#!/usr/bin/awk -f

# ./mk_theme.sh perm \
# '([-d])([-r])([-w])([-x])([-r])([-w])([-x])([-r])([-w])([-x])' 'b' 'g,' 'g,i' 'g,o' 'y,' 'y,i' 'y,o' 'r,' 'r,i' 'r,o'

# gawk profile, created Mon Feb 20 23:47:29 2017

# BEGIN rule(s)

BEGIN {
	colors0[0] = ";34"
	colors0[1] = ";32"
	colors0[2] = ";32;3"
	colors0[3] = ";32;1"
	colors0[4] = ";33"
	colors0[5] = ";33;3"
	colors0[6] = ";33;1"
	colors0[7] = ";31"
	colors0[8] = ";31;3"
	colors0[9] = ";31;1"
	nb_colors0 = 10
}

# Rule(s)

{
	s = ""
	if (match($0, /([-d])([-r])([-w])([-x])([-r])([-w])([-x])([-r])([-w])([-x])/, a)) {
		n = length(a) / 3
		if (n == 1) {
			i = 0
			ic = 0
			s = s substr($0, 0, RSTART - 1) "\033[" colors0[ic % nb_colors0] "m" a[i] "\033[0m"
		} else {
			c = ""
			p = 1
			for (i = 1; i < n; ++i) {
				start = a[i, "start"]
				if (start == null) {
					++n
					continue
				}
				ic = i - 1
				s = s substr($0, p, start - p) "\033[" colors0[ic % nb_colors0] "m" a[i] "\033[0m"
				p = start + a[i, "length"]
			}
			s = s substr($0, p, RSTART + RLENGTH - p)
		}
		$0 = substr($0, RLENGTH + RSTART)
	}
	print s $0
}

